### ISSUE TITLE
Errores en la página

### ISSUE THREAD

**Issue by vcanalesp** [fralfaro/pyschool_content#1]
### Home

En el cronograma la hora de término debería decir 13:30

La siguiente opción no renderiza bien, sale error 404

Taller 2: Opcional, según la elección de cada participante:
- [Python en Ciencia de Datos](https://pyschool.cl/talleres/taller_3.qmd.html)

### Taller 1

Ejercicio : Código para Conversión de Temperatura

Explicación del Código
Fórmula de Conversión:
- La función utiliza la fórmula *((celsius ) + 32)* para convertir la temperatura a grados Fahrenheit y devuelve el resultado.

En la fórmula falta un 9/5, debería ser *(celsius * 9/5) + 32*

Ejercicio: Número Primo

Explicación del Código
2. Lógica de Verificación:
- Usa un bucle *for para iterar desde 2 hasta la raíz cuadrada de n*. Si n es divisible por cualquier número en este rango, la función devuelve False indicando que no es un número primo.

En el ciclo for falta un + 1, debería ser *for para iterar desde 2 hasta la raíz cuadrada de n + 1*

**Comment by fralfaro** [comment]
Se corrigen errores en esta nueva versión:  https://github.com/fralfaro/pyschool_content
